workloads:
  hello-pod:
    runtime: podman-kube
    agent: agent_B
    restart: true
    updateStrategy: AT_MOST_ONCE
    accessRights:
      allow: []
      deny: []
    tags:
      - key: owner
        value: Ankaios team
    runtimeConfig: |
      manifest: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: hello-pod
        spec:
          restartPolicy: Never
          containers:
          - name: looper
            image: alpine:latest
            command: 
            - sleep
            - 50000
          - name: greater
            image: alpine:latest
            command: 
            - echo
            - "Hello from a container in a pod"
        ---
        apiVersion: v1
        kind: Pod
        metadata:
          name: hello2-pod
        spec:
          restartPolicy: Never
          containers:
          - name: looper
            image: alpine:latest
            command: 
            - sleep
            - 50000
          - name: greater
            image: alpine:latest
            command: 
            - echo
            - "Hello from a container in a pod"
