name: PR Task List Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  verify:
    name: verify_pr_task_list
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check tasklist
        uses: Awayume/github-pr-tasklist-checker@v1.0.0
